version: "3.3"

services:
    prestashop_web:
        networks: 
            - prestashop_net
        volumes:
            - prestashop-data:/var/www/html
        ports:
            - 8080:80
        build:
            context: ./docker/prestashop_web
            dockerfile: Dockerfile

    prestashop_db_server:
        networks: 
            - prestashop_net
        volumes:
            - /var/prestashop_vla/prestashop_db_server:/var/lib/mysql
        ports: 
            - 3307:3306
        env_file:
            - ./docker/prestashop_db_server/.env
        build:
            context: ./docker/prestashop_db_server
            dockerfile:  Dockerfile

    php_my_admin:
        networks: 
            - prestashop_net
        ports:
            - 8081:80
        env_file:
            - ./docker/php_my_admin/.env
        build:
            context: ./docker/php_my_admin
            dockerfile:  Dockerfile

volumes:
    prestashop-data: {}
networks:
    prestashop_net:
        driver: bridge